aws_access_key_id: 'your_aws_access_key_id_that_should_be_stored_in_system_ENV'
aws_secret_access_key: 'your_aws_secret_access_key_that_should_be_stored_in_system_ENV'
s3_bucket_name: 'your_s3_bucket_name'
